# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20160614_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='debut_date',
            field=models.DateField(null=True, verbose_name='Artist debut date'),
        ),
    ]
