# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_auto_20160615_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicservice',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug name'),
        ),
    ]
