# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_auto_20160616_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateHourlySongChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(unique=True, verbose_name='Chart start hour')),
                ('charts', models.ManyToManyField(to='charts.HourlySongChart')),
            ],
            options={
                'ordering': ['-hour'],
            },
        ),
        migrations.CreateModel(
            name='AggregateHourlySongChartEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(verbose_name='Chart position')),
                ('total_score', models.FloatField(default=0.0, verbose_name='Total song score')),
                ('hourly_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='charts.AggregateHourlySongChart')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.Song')),
            ],
            options={
                'ordering': ['hourly_chart', 'position'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='aggregatehourlysongchartentry',
            unique_together=set([('hourly_chart', 'song')]),
        ),
    ]
