# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_auto_20160618_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggregatehourlysongchartentry',
            old_name='total_score',
            new_name='score',
        ),
    ]
