# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0007_auto_20160618_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatehourlysongchartentry',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='Aggregated song score'),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatehourlysongchartentry',
            unique_together=set([('hourly_chart', 'song'), ('hourly_chart', 'position')]),
        ),
    ]
