# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_auto_20160618_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatehourlysongchartentry',
            name='prev_position',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='Previous chart position'),
        ),
        migrations.AddField(
            model_name='hourlysongchartentry',
            name='prev_position',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='Previous chart position'),
        ),
    ]
